import {getSession,signIn,signOut,getCatalog,getInstructorProfile,createLiveSession,getLiveSessions,updateLiveSession,deleteLiveSession,createQuestion,createTheme,createChapterAndQuiz,updateQuestion,deleteQuestionById,updateAnswerOption,deleteThemeById,deleteChapterById,rpc} from './api.js';
const app=document.querySelector('#app');let catalog=[],live=[],pilotPoller=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const flat=()=>catalog.flatMap(t=>(t.chapters||[]).map(c=>({theme:t,chapter:c,quiz:Array.isArray(c.quizzes)?c.quizzes[0]:c.quizzes})));
const learnerOrigin=location.origin;
const urlFor=code=>`${learnerOrigin}/learner.html?session=${encodeURIComponent(code)}`;
const code=()=>Array.from(crypto.getRandomValues(new Uint8Array(8)),value=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[value%32]).join('');
const qr=c=>`/api/qr?code=${encodeURIComponent(c)}`;
function shell(body){app.innerHTML=`<header class="topbar"><a class="brand" href="./instructor.html"><span class="logo">TS</span><span>Formation <small>· Instructeur</small></span></a><a class="link-button" href="./learner.html">🎓 Apprenant</a></header><main class="container animate-in">${body}</main>`}
function togglePassword(inputId,button){const input=document.querySelector(`#${inputId}`);if(!input)return;const visible=input.type==='text';input.type=visible?'password':'text';button.textContent=visible?'👁️':'🙈';button.setAttribute('aria-label',visible?'Afficher le mot de passe':'Masquer le mot de passe');button.title=visible?'Afficher le mot de passe':'Masquer le mot de passe'}
function login(){shell(`<div class="login"><p class="eyebrow">Accès instructeur / auditeur</p><h1>Connexion</h1><div class="card"><label>Email</label><input id="email" type="email" autocomplete="email"><label>Mot de passe</label><div class="password-field"><input id="password" type="password" autocomplete="current-password"><button class="password-toggle" type="button" aria-label="Afficher le mot de passe" title="Afficher le mot de passe" onclick="togglePassword('password',this)">👁️</button></div><p><button class="button" onclick="doLogin()">Se connecter →</button></p><p id="error" class="notice hidden"></p></div></div>`)}
async function doLogin(){try{await signIn(document.querySelector('#email').value,document.querySelector('#password').value);await load();render()}catch(e){const x=document.querySelector('#error');x.textContent=e.message;x.classList.remove('hidden')}}
async function load(){[catalog,live]=await Promise.all([getCatalog(),getLiveSessions()])}
function render(){if(!getSession())return login();const items=flat();shell(`<div class="layout"><aside class="sidebar"><p>Navigation</p><button class="nav-button active" onclick="panel('create',this)">📡 Sessions live</button><button class="nav-button" onclick="panel('questions',this)">🧩 Questions</button><button class="nav-button" onclick="panel('pilot',this)">🎮 Piloter le quiz</button><button class="nav-button" onclick="panel('scheduled',this)">🗓️ Quiz programmés</button><button class="nav-button" onclick="panel('performance',this)">🏆 Performances</button><button class="nav-button" onclick="logout()">↪ Déconnexion</button></aside><section><div id="create" class="panel active"><p class="eyebrow">Créer et diffuser</p><h1>Nouvelle session live ✦</h1><div class="card"><label>Thème · chapitre</label><select id="quizSelect">${items.map(i=>`<option value="${i.quiz?.id}">${esc(i.theme.name)} · ${esc(i.chapter.title)}</option>`).join('')}</select><label>Nom de la session</label><input id="sessionTitle" placeholder="Ex. Formation équipe matin"><p><button class="button" onclick="createSession()">Générer le QR code ✨</button></p></div><div id="createdSession"></div></div><div id="questions" class="panel"><div class="row"><div><p class="eyebrow">Bibliothèque</p><h1>Questions par thème</h1></div><button class="button" onclick="showQuestionForm()">＋ Ajouter une question</button></div><div id="questionForm"></div><div class="tabs theme-tags">${catalog.map((t,i)=>`<button class="tab ${i?'':'active'}" onclick="showTheme('${t.id}',this)">🏷️ ${esc(t.name)}</button>`).join('')}</div><div id="accordions" class="accordion-list"></div></div><div id="pilot" class="panel"><p class="eyebrow">Contrôle direct</p><div class="row"><h1>Piloter le quiz</h1><button class="button secondary" onclick="refresh()">↻ Actualiser</button></div><div id="pilotRows"></div></div><div id="scheduled" class="panel"><h1>Quiz programmés</h1><div class="card table-wrap"><table><thead><tr><th>Code</th><th>Quiz</th><th>État</th><th>Participants</th></tr></thead><tbody>${live.map(s=>`<tr><td>${s.code}</td><td>${esc(titleFor(s.quiz_id))}</td><td><span class="tag">${s.status}</span></td><td>${(s.session_participants||[]).length}</td></tr>`).join('')||'<tr><td colspan="4">Aucune session.</td></tr>'}</tbody></table></div></div><div id="performance" class="panel"><h1>Performances individuelles</h1><select id="performanceSelect" onchange="showPerformance()"><option value="">Sélectionner une session</option>${live.map(s=>`<option value="${s.id}">${s.code} · ${esc(titleFor(s.quiz_id))}</option>`).join('')}</select><div id="performanceRows" class="card" style="margin-top:18px">Sélectionnez une session.</div></div></section></div>`);showTheme(catalog[0]?.id);renderPilot()}
function panel(id,b){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav-button').forEach(x=>x.classList.remove('active'));b?.classList.add('active');if(id==='pilot')startPilotAutoRefresh();else stopPilotAutoRefresh()}
function startPilotAutoRefresh(){if(pilotPoller)return;pilotPoller=setInterval(async()=>{if(!document.querySelector('#pilot.panel.active'))return stopPilotAutoRefresh();try{live=await getLiveSessions();renderPilot()}catch(error){console.error(error)}},1500)}
function stopPilotAutoRefresh(){if(!pilotPoller)return;clearInterval(pilotPoller);pilotPoller=null}
function titleFor(quizId){return flat().find(i=>i.quiz?.id===quizId)?.quiz?.title||'Quiz'}
function showTheme(id,b){document.querySelectorAll('.theme-tags .tab').forEach(x=>x.classList.remove('active'));b?.classList.add('active');const theme=catalog.find(t=>t.id===id),box=document.querySelector('#accordions');if(!box||!theme)return;box.innerHTML=`<div class="library-actions"><span class="tag">Thème sélectionné · ${esc(theme.name)}</span><button class="icon-button danger" title="Supprimer ce thème" aria-label="Supprimer le thème" onclick="removeTheme('${theme.id}')">🗑️</button></div>`+(theme.chapters||[]).map(c=>{const qz=Array.isArray(c.quizzes)?c.quizzes[0]:c.quizzes;return `<details class="chapter-accordion"><summary><span class="chapter-icon">📚</span><span><b>${esc(c.title)}</b><small>${qz?.questions?.length||0} question(s)</small></span><button class="icon-button danger" type="button" title="Supprimer ce chapitre" aria-label="Supprimer le chapitre" onclick="event.preventDefault();event.stopPropagation();removeChapter('${c.id}')">🗑️</button><span class="chevron">⌄</span></summary><div class="chapter-content">${(qz?.questions||[]).map((q,n)=>`<article class="question-row"><span class="question-number">${n+1}</span><div style="flex:1"><div class="question-title"><b>${esc(q.body)}</b><span class="question-actions"><button class="icon-button" type="button" title="Modifier la question" aria-label="Modifier la question" onclick="editQuestion('${q.id}')">✏️</button><button class="icon-button danger" type="button" title="Supprimer la question" aria-label="Supprimer la question" onclick="removeQuestion('${q.id}')">🗑️</button></span></div><div class="answer-preview">${(q.answer_options||[]).map(o=>`<button class="answer-chip" title="Modifier la proposition" onclick="editOption('${o.id}')">${o.label} · ${esc(o.body)} ✏️</button>`).join('')}</div></div></article>`).join('')||'<p class="muted">Aucune question dans ce chapitre.</p>'}</div></details>`}).join('')}
function optionEntry(id){for(const theme of catalog){for(const chapter of theme.chapters||[]){const quiz=Array.isArray(chapter.quizzes)?chapter.quizzes[0]:chapter.quizzes;for(const question of quiz?.questions||[]){const option=(question.answer_options||[]).find(item=>item.id===id);if(option)return{theme,question,option}}}}return null}
async function editOption(id){const entry=optionEntry(id);if(!entry)return alert('Proposition introuvable.');showQuestionForm(entry.question.id)}
function questionEntry(id){for(const theme of catalog){for(const chapter of theme.chapters||[]){const quiz=Array.isArray(chapter.quizzes)?chapter.quizzes[0]:chapter.quizzes;const question=(quiz?.questions||[]).find(item=>item.id===id);if(question)return{theme,chapter,question}}}return null}
async function editQuestion(id){const entry=questionEntry(id);if(!entry)return alert('Question introuvable.');showQuestionForm(id)}
async function removeQuestion(id){const entry=questionEntry(id);if(!entry)return;const label=`Question ${entry.question.position||''} · ${entry.question.body}`.trim();if(!confirm(`Supprimer définitivement « ${label} » ?\n\nSes propositions seront également supprimées. Cette action est irréversible.`))return;try{await deleteQuestionById(id);await refreshQuestions(entry.theme.id)}catch(error){alert(`Suppression impossible : ${error.message}\n\nSi cette question a déjà été utilisée dans une session, elle doit être conservée pour préserver les résultats.`)}}
async function removeTheme(id){const theme=catalog.find(item=>item.id===id);if(!theme)return;const chapters=theme.chapters||[];if(!confirm(`Supprimer définitivement le thème « ${theme.name} » ?\n\nCela supprimera aussi ${chapters.length} chapitre(s), leurs quiz, questions et propositions. Cette action est irréversible.`))return;try{await deleteThemeById(id);await load();render();panel('questions');showTheme(catalog[0]?.id)}catch(e){alert(`Suppression impossible : ${e.message}\n\nSi ce thème a déjà été utilisé dans une session live, terminez ou supprimez d’abord les sessions associées.`)}}
async function removeChapter(id){let entry=null;for(const theme of catalog){const chapter=(theme.chapters||[]).find(item=>item.id===id);if(chapter){entry={theme,chapter};break}}if(!entry)return;const quiz=Array.isArray(entry.chapter.quizzes)?entry.chapter.quizzes[0]:entry.chapter.quizzes;const count=quiz?.questions?.length||0;if(!confirm(`Supprimer définitivement le chapitre « ${entry.chapter.title} » ?\n\nSon quiz, ses ${count} question(s) et leurs propositions seront supprimés. Cette action est irréversible.`))return;try{await deleteChapterById(id);await refreshQuestions(entry.theme.id)}catch(e){alert(`Suppression impossible : ${e.message}\n\nSi ce chapitre a déjà été utilisé dans une session live, terminez ou supprimez d’abord les sessions associées.`)}}
async function refreshQuestions(themeId){await load();render();panel('questions');showTheme(themeId)}
async function createSession(){try{const profile=await getInstructorProfile(),quizId=document.querySelector('#quizSelect').value,title=document.querySelector('#sessionTitle').value.trim()||titleFor(quizId),s=await createLiveSession({code:code(),quiz_id:quizId,instructor_id:profile.id,status:'waiting'});await load();render();document.querySelector('#createdSession').innerHTML=`<div class="card center pop-in"><span class="tag">Session créée</span><h2>${esc(title)}</h2><img class="generated-qr" src="${qr(s.code)}"><div class="code">${s.code}</div><input readonly value="${esc(urlFor(s.code))}"></div>`}catch(e){alert(e.message)}}
function quizForSession(s){return flat().find(i=>i.quiz?.id===s.quiz_id)?.quiz}
function participantName(participant){return `${participant.app_users?.first_name||''} ${participant.app_users?.last_name||''}`.trim()||'Participant'}
function participantInitials(participant){return `${participant.app_users?.first_name?.[0]||''}${participant.app_users?.last_name?.[0]||''}`.toUpperCase()||'?' }
function selectedLabels(session,question,participantId){const labels=new Map((question?.answer_options||[]).map(option=>[option.id,option.label]));return (session.live_answers||[]).filter(answer=>answer.question_id===question?.id&&answer.participant_id===participantId).map(answer=>labels.get(answer.option_id)).filter(Boolean).sort()}
function submissionFor(session,questionId,participantId){return (session.live_answer_submissions||[]).find(item=>item.question_id===questionId&&item.participant_id===participantId)}
function renderArrivalBoard(session,waiting){if(!waiting.length)return '';return `<section class="arrival-board"><div class="row"><div><p class="eyebrow">Tableau des arrivées</p><h3>Participants en attente</h3></div><span class="count-badge">${waiting.length}</span></div><div class="arrival-grid">${waiting.map(participant=>`<button class="arrival-person" type="button" onclick="approve('${participant.id}')" title="Accepter ce participant"><span class="avatar-initials">${esc(participantInitials(participant))}</span><span><b>${esc(participantName(participant))}</b><small>en attente · cliquer pour accepter</small></span></button>`).join('')}</div><button class="button accept-all" type="button" onclick="approveAll('${session.id}')">✓ Accepter tout le monde</button></section>`}
function renderResponseTracking(session,quiz){const question=(quiz?.questions||[]).find(item=>item.id===session.current_question_id);if(!question)return '';const participants=(session.session_participants||[]).filter(item=>item.status==='joined'),options=question.answer_options||[];return `<section class="response-tracking"><div class="row"><div><p class="eyebrow">Suivi détaillé</p><h3>Réponses à la question ${question.position||''}</h3></div><span class="tag">${participants.length} participant(s)</span></div><p class="muted response-question">${esc(question.body)}</p><div class="table-wrap"><table class="response-matrix"><thead><tr><th>Participant</th>${options.map(option=>`<th title="${esc(option.body)}">${option.label}</th>`).join('')}<th>Résultat</th></tr></thead><tbody>${participants.map(participant=>{const labels=new Set(selectedLabels(session,question,participant.id)),submission=submissionFor(session,question.id,participant.id);return `<tr><td><b>${esc(participantName(participant))}</b></td>${options.map(option=>`<td class="matrix-cell ${labels.has(option.label)?'selected':''}">${labels.has(option.label)?'✓':'—'}</td>`).join('')}<td>${submission?`<span class="result-pill ${submission.is_correct?'correct':'incorrect'}">${submission.is_correct?'Correct':'Incorrect'}</span>`:'<span class="result-pill pending">En attente</span>'}</td></tr>`}).join('')||`<tr><td colspan="${options.length+2}">Aucun participant admis.</td></tr>`}</tbody></table></div></section>`}
function renderPilot(){const box=document.querySelector('#pilotRows');if(!box)return;box.innerHTML=live.length?live.map(session=>{const quiz=quizForSession(session),target=(quiz?.questions||[]).find(question=>question.id===session.current_question_id)||quiz?.questions?.[0],waiting=(session.session_participants||[]).filter(participant=>participant.status==='waiting_list'),joined=(session.session_participants||[]).filter(participant=>participant.status==='joined'),hasQuestion=Boolean(session.current_question_id),canPoll=session.status==='live'||session.status==='polling',answered=new Set((session.live_answer_submissions||[]).filter(item=>item.question_id===session.current_question_id).map(item=>item.participant_id)).size,allAnswered=session.status==='live'&&joined.length>0&&answered>=joined.length,pollLabel=allAnswered?'✓ Tout le monde a répondu — afficher le sondage':'📊 Afficher le sondage';return `<article class="card session-control-card"><div class="row"><h2>${session.code} · ${esc(quiz?.title||'Quiz')}</h2><span class="tag">${session.status}</span></div><div class="actions"><button class="button" onclick="start('${session.id}','${target?.id||''}')">▶ Lancer / reprendre</button><button class="button secondary ${allAnswered?'poll-ready':''}" onclick="pause('${session.id}')" ${canPoll?'':'disabled'}>${pollLabel}</button><button class="button secondary" onclick="next('${session.id}')" ${hasQuestion?'':'disabled'}>Suivant →</button><button class="button danger" onclick="finish('${session.id}')">■ Terminer</button><button class="button danger" onclick="removeLiveSession('${session.id}','${esc(session.code)}')">🗑️ Supprimer</button></div>${hasQuestion?`<p class="response-progress ${allAnswered?'complete':''}">${answered}/${joined.length} participant(s) ont répondu à cette question.</p>`:''}<p class="muted">Le sondage ne s’affiche aux apprenants qu’après un clic sur « Afficher le sondage ».</p>${renderArrivalBoard(session,waiting)}${renderResponseTracking(session,quiz)}</article>`}).join(''):'<div class="card empty">Créez une session avant de la piloter.</div>'}
async function start(id,qid){if(!qid)return alert('Aucune question disponible.');const session=live.find(item=>item.id===id),question=(quizForSession(session)?.questions||[]).find(item=>item.id===qid),duration=Math.max(5,Number(question?.duration_seconds)||30);await updateLiveSession(id,{status:'live',current_question_id:qid,question_started_at:new Date().toISOString(),question_ends_at:new Date(Date.now()+duration*1000).toISOString()});await refresh()}
async function pause(id){await updateLiveSession(id,{status:'polling'});await refresh()}
async function next(id){const s=live.find(x=>x.id===id),q=(quizForSession(s)?.questions||[]),i=q.findIndex(x=>x.id===s.current_question_id),nextQ=q[i+1];if(!nextQ)return finish(id);await updateLiveSession(id,{status:'waiting',current_question_id:nextQ.id,question_started_at:null,question_ends_at:null});await refresh()}
async function finish(id){await updateLiveSession(id,{status:'finished',ended_at:new Date().toISOString()});await refresh()}
async function removeLiveSession(id,sessionCode){if(!confirm(`Supprimer définitivement la session ${sessionCode} ?\n\nLes participants, réponses et résultats associés seront supprimés. Cette action est irréversible.`))return;try{await deleteLiveSession(id);await refresh()}catch(e){alert(`Suppression impossible : ${e.message}`)}}
async function approve(id){await rpc('approve_live_participant',{p_participant_id:id});await refresh()}
async function approveAll(sessionId){const session=live.find(item=>item.id===sessionId),waiting=(session?.session_participants||[]).filter(item=>item.status==='waiting_list');try{for(const participant of waiting)await rpc('approve_live_participant',{p_participant_id:participant.id});await refresh()}catch(error){alert(error.message)}}
async function refresh(){await load();render();panel('pilot')}
async function showPerformance(){const selected=document.querySelector('#performanceSelect').value,box=document.querySelector('#performanceRows');if(!selected)return;await load();const session=live.find(item=>item.id===selected);if(!session)return;const quiz=quizForSession(session),questions=quiz?.questions||[],participants=(session.session_participants||[]).filter(item=>item.status==='joined'),submissions=session.live_answer_submissions||[],questionCount=questions.length;box.innerHTML=`<p class="muted">Chaque colonne indique la ou les propositions choisies par l’apprenant. Survolez une réponse pour voir son libellé.</p><div class="table-wrap"><table class="performance-table"><thead><tr><th>Apprenant</th>${questions.map(question=>`<th title="${esc(question.body)}">Q${question.position||questions.indexOf(question)+1}</th>`).join('')}<th>Réponses</th><th>Bonnes réponses</th><th>Score</th></tr></thead><tbody>${participants.map(participant=>{const mine=submissions.filter(item=>item.participant_id===participant.id),correct=mine.filter(item=>item.is_correct).length;return `<tr><td><b>${esc(participantName(participant))}</b></td>${questions.map(question=>{const labels=selectedLabels(session,question,participant.id),submission=submissionFor(session,question.id,participant.id),detail=(question.answer_options||[]).filter(option=>labels.includes(option.label)).map(option=>`${option.label} · ${option.body}`).join(' | ');return `<td title="${esc(detail||'Aucune réponse')}">${labels.length?`<span class="performance-choice ${submission?.is_correct?'correct':'incorrect'}">${labels.join(', ')} ${submission?.is_correct?'✓':'✕'}</span>`:'—'}</td>`}).join('')}<td>${mine.length}/${questionCount}</td><td>${correct}</td><td><b>${questionCount?Math.round(correct*100/questionCount):0}%</b></td></tr>`}).join('')||`<tr><td colspan="${questionCount+4}">Aucun apprenant admis.</td></tr>`}</tbody></table></div>`}
async function logout(){await signOut();login()}
function chapterOptions(themeId){const theme=catalog.find(t=>t.id===themeId);return (theme?.chapters||[]).map(c=>{const qz=Array.isArray(c.quizzes)?c.quizzes[0]:c.quizzes;return `<option value="${c.id}" data-quiz="${qz?.id||''}" ${qz?'':'disabled'}>${esc(c.title)}${qz?'':' (quiz indisponible)'}</option>`}).join('')}
function showQuestionForm(questionId=''){const box=document.querySelector('#questionForm');if(!box)return;const entry=questionId?questionEntry(questionId):null;if(questionId&&!entry)return alert('Question introuvable.');const editing=Boolean(entry),question=entry?.question,options=['A','B','C','D'].map(label=>(question?.answer_options||[]).find(option=>option.label===label));const themeId=entry?.theme.id||catalog[0]?.id,chapterId=entry?.chapter.id||'';box.innerHTML=`<form class="card question-form" onsubmit="submitQuestion(event,'${question?.id||''}')"><div class="row"><h2>${editing?'Modifier la question':'Ajouter une question'}</h2><button type="button" class="button secondary" onclick="closeQuestionForm()">Fermer</button></div><p class="muted">${editing?'Modifiez l’énoncé, les propositions, les bonnes réponses ou la durée.':'Choisissez une structure existante, ou créez un thème et un chapitre dans la base OVH.'}</p><div class="form-grid"><div><label>Thème</label><select id="questionTheme" onchange="syncQuestionChapters()" ${editing?'disabled':''}>${catalog.map(t=>`<option value="${t.id}" ${t.id===themeId?'selected':''}>${esc(t.name)}</option>`).join('')}</select></div>${editing?'':`<div><label>Nouveau thème <small>(facultatif)</small></label><input id="newTheme" placeholder="Ex. Sécurité biologique"></div>`}<div><label>Chapitre</label><select id="questionChapter" ${editing?'disabled':''}>${chapterOptions(themeId)}</select></div>${editing?'':`<div><label>Nouveau chapitre <small>(facultatif)</small></label><input id="newChapter" placeholder="Ex. Les équipements de protection"></div>`}<div class="full"><label>Question</label><textarea id="questionBody" required placeholder="Saisissez l’énoncé de la question">${esc(question?.body||'')}</textarea></div>${['A','B','C','D'].map((label,index)=>`<div><label>Proposition ${label}</label><input id="answer${index}" required placeholder="Réponse ${label}" value="${esc(options[index]?.body||'')}"></div>`).join('')}<div class="full"><label>Bonne(s) réponse(s)</label><p class="muted">Cochez toutes les propositions correctes. Une ou plusieurs réponses peuvent être justes.</p><div class="correct-choices">${['A','B','C','D'].map((label,index)=>`<label class="inline-choice"><input class="correctAnswer" type="checkbox" value="${index}" ${(editing?options[index]?.is_correct:index===0)?'checked':''}> Proposition ${label}</label>`).join('')}</div></div><div><label>Durée (secondes)</label><input id="questionSeconds" type="number" min="5" max="3600" value="${Number(question?.duration_seconds)||30}" required></div></div><p id="questionError" class="notice hidden"></p><p><button class="button" type="submit">${editing?'Enregistrer les modifications':'Enregistrer la question'} ✓</button></p></form>`;if(editing){const chapterSelect=document.querySelector('#questionChapter');if(chapterSelect)chapterSelect.value=chapterId}box.scrollIntoView({behavior:'smooth',block:'start'})}
function closeQuestionForm(){const box=document.querySelector('#questionForm');if(box)box.innerHTML=''}
function syncQuestionChapters(){const select=document.querySelector('#questionChapter'),themeId=document.querySelector('#questionTheme')?.value;if(select)select.innerHTML=chapterOptions(themeId)}
async function submitQuestion(event,questionId=''){event.preventDefault();const chapter=document.querySelector('#questionChapter'),error=document.querySelector('#questionError'),newTheme=document.querySelector('#newTheme')?.value.trim()||'',newChapter=document.querySelector('#newChapter')?.value.trim()||'';try{const correct=[...document.querySelectorAll('.correctAnswer:checked')].map(input=>Number(input.value));if(!correct.length)throw new Error('Choisissez au moins une bonne réponse.');const answers=[0,1,2,3].map(i=>document.querySelector(`#answer${i}`).value.trim()),payload={body:document.querySelector('#questionBody').value.trim(),answers,correct,seconds:Number(document.querySelector('#questionSeconds').value),explanation:null};if(questionId){const entry=questionEntry(questionId);if(!entry)throw new Error('Question introuvable.');await updateQuestion(questionId,payload);await load();render();panel('questions');showTheme(entry.theme.id);alert('Question mise à jour sur OVH.');return}let quizId=chapter?.selectedOptions?.[0]?.dataset.quiz;if(newTheme){const theme=await createTheme(newTheme);if(!newChapter)throw new Error('Ajoutez aussi le premier chapitre de ce nouveau thème.');quizId=(await createChapterAndQuiz(theme.id,newChapter)).quiz.id}else if(newChapter){quizId=(await createChapterAndQuiz(document.querySelector('#questionTheme').value,newChapter)).quiz.id}if(!quizId)throw new Error('Ce chapitre n’a pas encore de quiz associé.');await createQuestion(quizId,payload);await load();render();panel('questions');showQuestionForm();alert('Question, thème et chapitre enregistrés sur OVH.')}catch(e){error.textContent=e.message;error.classList.remove('hidden')}}
Object.assign(window,{togglePassword,doLogin,panel,showTheme,showQuestionForm,closeQuestionForm,syncQuestionChapters,submitQuestion,editOption,editQuestion,removeQuestion,removeTheme,removeChapter,createSession,renderPilot,start,pause,next,finish,removeLiveSession,approve,approveAll,refresh,showPerformance,logout});
load().then(render).catch(login);
