import {
  getSession, signIn, signOut, getInstructorProfile, getInstructors, createInstructor,
  setInstructorStatus, resetInstructorPassword, getArchives, restoreArchive, deleteArchive,
  getAuditLogs
} from './api.js';

const app=document.querySelector('#superadminApp');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const typeLabels={session:'Session live',group:'Groupe de formation',exam:'Examen final',experience:'Expérience pratique',certificate:'Certificat',participant:'Participant',question:'Question'};
let profile=null;
let instructors=[];
let instructorMaximum=5;
let archives=[];
let archivePage=0;
let auditPage=1;
let auditSearch='';
let activePanel='instructors';

function shell(body){app.innerHTML=`<header class="topbar"><a class="brand" href="./superadmin.html"><span class="logo">TS</span><span>Formation <small>· Superadministration</small></span></a><span class="topbar-actions"><a class="link-button" href="./instructor.html">← Espace instructeur</a>${profile?'<button class="link-button" type="button" onclick="logout()">Déconnexion</button>':''}</span></header><main class="container animate-in">${body}</main>`}

function login(){shell(`<div class="login"><p class="eyebrow">Accès réservé</p><h1>Superadministration</h1><div class="card"><label>Adresse e-mail</label><input id="adminEmail" type="email" autocomplete="email"><label>Mot de passe</label><input id="adminPassword" type="password" autocomplete="current-password"><p><button class="button" onclick="doLogin()">Se connecter →</button></p><p id="loginError" class="notice hidden"></p></div></div>`)}

async function doLogin(){try{await signIn(document.querySelector('#adminEmail').value,document.querySelector('#adminPassword').value);await start()}catch(error){const box=document.querySelector('#loginError');box.textContent=error.message;box.classList.remove('hidden')}}

function layout(){shell(`<div class="layout superadmin-layout"><aside class="sidebar"><p>Administration</p><button class="nav-button ${activePanel==='instructors'?'active':''}" onclick="openPanel('instructors',this)">👤 Instructeurs</button><button class="nav-button ${activePanel==='archives'?'active':''}" onclick="openPanel('archives',this)">🗃️ Archives</button><button class="nav-button ${activePanel==='journal'?'active':''}" onclick="openPanel('journal',this)">🧾 Journal centralisé</button></aside><section><div id="instructors" class="panel ${activePanel==='instructors'?'active':''}"></div><div id="archives" class="panel ${activePanel==='archives'?'active':''}"></div><div id="journal" class="panel ${activePanel==='journal'?'active':''}"></div></section></div>`)}

async function loadInstructors(){const result=await getInstructors();instructors=result.instructors||[];instructorMaximum=result.maximum||5;renderInstructors()}

function renderInstructors(){const box=document.querySelector('#instructors');if(!box)return;const active=instructors.filter(item=>!item.archived_at).length;box.innerHTML=`<div class="row"><div><p class="eyebrow">Gestion des accès</p><h1>Comptes instructeurs</h1></div><span class="tag">${active}/${instructorMaximum} actifs</span></div><form class="card instructor-account-form" onsubmit="submitInstructor(event)"><h2>Créer un instructeur</h2><div class="form-grid"><div><label>Prénom</label><input id="instructorFirstName" required maxlength="100"></div><div><label>Nom</label><input id="instructorLastName" required maxlength="100"></div><div><label>Adresse e-mail</label><input id="instructorEmail" type="email" required maxlength="254"></div><div><label>Mot de passe initial</label><input id="instructorPassword" type="password" minlength="12" required autocomplete="new-password"></div></div><p class="muted">Le mot de passe doit contenir au moins 12 caractères. Le nombre de comptes actifs est limité à ${instructorMaximum}.</p><button class="button" ${active>=instructorMaximum?'disabled':''}>Créer le compte</button></form><div class="card table-wrap"><table><thead><tr><th>Instructeur</th><th>Identifiant</th><th>Dernière connexion</th><th>État</th><th>Actions</th></tr></thead><tbody>${instructors.map(item=>`<tr><td><b>${esc(item.first_name)} ${esc(item.last_name)}</b></td><td>${esc(item.email)}</td><td>${formatDate(item.last_login_at)}</td><td><span class="result-pill ${item.archived_at?'pending':'correct'}">${item.archived_at?'Désactivé':'Actif'}</span></td><td><div class="row-actions"><button class="icon-button" type="button" onclick="changeInstructorStatus('${item.id}',${item.archived_at?'true':'false'})" title="${item.archived_at?'Réactiver':'Désactiver'}">${item.archived_at?'✅':'⛔'}</button><button class="icon-button" type="button" onclick="changeInstructorPassword('${item.id}')" title="Réinitialiser le mot de passe">🔑</button></div></td></tr>`).join('')||'<tr><td colspan="5">Aucun compte instructeur.</td></tr>'}</tbody></table></div>`}

async function submitInstructor(event){event.preventDefault();try{await createInstructor({first_name:document.querySelector('#instructorFirstName').value.trim(),last_name:document.querySelector('#instructorLastName').value.trim(),email:document.querySelector('#instructorEmail').value.trim(),password:document.querySelector('#instructorPassword').value});await loadInstructors()}catch(error){alert(error.message)}}
async function changeInstructorStatus(id,active){if(!confirm(active?'Réactiver ce compte instructeur ?':'Désactiver ce compte ? Ses sessions de connexion ouvertes seront fermées.'))return;try{await setInstructorStatus(id,active);await loadInstructors()}catch(error){alert(error.message)}}
async function changeInstructorPassword(id){const item=instructors.find(instructor=>instructor.id===id),name=item?`${item.first_name} ${item.last_name}`:'cet instructeur',password=prompt(`Nouveau mot de passe pour ${name} (12 caractères minimum) :`);if(password===null)return;if(password.length<12)return alert('Le mot de passe doit contenir au moins 12 caractères.');if(!confirm('Enregistrer ce nouveau mot de passe et fermer les sessions ouvertes de cet instructeur ?'))return;try{await resetInstructorPassword(id,password);alert('Mot de passe réinitialisé.')}catch(error){alert(error.message)}}

async function loadArchives(){archives=await getArchives();archivePage=Math.min(archivePage,Math.max(0,Math.ceil(archives.length/10)-1));renderArchives()}
function renderArchives(){const box=document.querySelector('#archives');if(!box)return;const start=archivePage*10,items=archives.slice(start,start+10);box.innerHTML=`<div class="row"><div><p class="eyebrow">Conservation manuelle</p><h1>Archives</h1></div><button class="button secondary" onclick="exportArchives()">Exporter la liste CSV</button></div><p class="muted">Vous pouvez restaurer un élément ou le supprimer définitivement. Une suppression définitive est irréversible.</p>${pagination(start,items.length,archives.length,'changeArchivePage')}<div class="card table-wrap"><table><thead><tr><th>Type</th><th>Élément</th><th>Détails</th><th>Archivé le</th><th>Actions</th></tr></thead><tbody>${items.map(item=>`<tr><td><span class="tag">${esc(typeLabels[item.type]||item.type)}</span></td><td><b>${esc(item.label)}</b></td><td>${esc(item.details||'—')}</td><td>${formatDate(item.archived_at)}</td><td><div class="row-actions"><button class="icon-button" onclick="restoreItem('${item.type}','${item.id}')" title="Restaurer">↩️</button><button class="icon-button danger" onclick="deleteItem('${item.type}','${item.id}')" title="Supprimer définitivement">🗑️</button></div></td></tr>`).join('')||'<tr><td colspan="5">Aucune archive.</td></tr>'}</tbody></table></div>${pagination(start,items.length,archives.length,'changeArchivePage')}`}
function changeArchivePage(direction){archivePage=Math.max(0,archivePage+direction);renderArchives()}
async function restoreItem(type,id){if(!confirm('Restaurer cet élément dans les listes actives ?'))return;try{await restoreArchive(type,id);await loadArchives()}catch(error){alert(error.message)}}
async function deleteItem(type,id){const item=archives.find(entry=>entry.type===type&&entry.id===id),label=item?.label||'cet élément';if(!confirm(`Supprimer définitivement « ${label} » ?\n\nCette action est irréversible. Vérifiez qu’une sauvegarde récente existe avant de continuer.`))return;try{await deleteArchive(type,id);await loadArchives()}catch(error){alert(error.message)}}
function exportArchives(){downloadCsv('archives-quiz.csv',[['Type','Élément','Détails','Date d’archivage'],...archives.map(item=>[typeLabels[item.type]||item.type,item.label,item.details||'',item.archived_at])])}

async function loadJournal(){const result=await getAuditLogs(auditPage,auditSearch);renderJournal(result)}
function renderJournal(result){const box=document.querySelector('#journal');if(!box)return;const items=result.items||[],start=(result.page-1)*result.page_size;box.innerHTML=`<div class="row"><div><p class="eyebrow">Traçabilité</p><h1>Journal centralisé</h1></div><button class="button secondary" onclick="exportJournal()">Exporter cette page CSV</button></div><form class="card audit-search" onsubmit="searchJournal(event)"><label>Rechercher une personne ou une action</label><div class="actions"><input id="auditSearch" value="${esc(auditSearch)}" placeholder="Ex. instructeur, session, certificat"><button class="button">Rechercher</button></div></form>${pagination(start,items.length,result.total,'changeAuditPage',result.page,result.page_size)}<div class="card table-wrap"><table><thead><tr><th>Date</th><th>Personne</th><th>Rôle</th><th>Action</th><th>Résultat</th></tr></thead><tbody>${items.map(item=>`<tr><td>${formatDate(item.created_at)}</td><td><b>${esc(item.actor_name||'Système')}</b><small>${esc(item.actor_email||'')}</small></td><td>${esc(item.actor_role||'—')}</td><td><b>${esc(item.summary)}</b><small>${esc(item.action)}</small></td><td><span class="result-pill ${item.outcome==='success'?'correct':'incorrect'}">${item.outcome==='success'?'Réussie':'Échec'}</span></td></tr>`).join('')||'<tr><td colspan="5">Aucune action trouvée.</td></tr>'}</tbody></table></div>${pagination(start,items.length,result.total,'changeAuditPage',result.page,result.page_size)}`;box.dataset.items=JSON.stringify(items)}
function searchJournal(event){event.preventDefault();auditSearch=document.querySelector('#auditSearch').value.trim();auditPage=1;loadJournal().catch(showError)}
function changeAuditPage(direction){auditPage=Math.max(1,auditPage+direction);loadJournal().catch(showError)}
function exportJournal(){const box=document.querySelector('#journal'),items=JSON.parse(box?.dataset.items||'[]');downloadCsv('journal-quiz.csv',[['Date','Personne','Identifiant','Rôle','Action','Code action','Résultat'],...items.map(item=>[item.created_at,item.actor_name||'Système',item.actor_email||'',item.actor_role||'',item.summary,item.action,item.outcome])])}

function pagination(start,count,total,handler,page=Math.floor(start/10)+1,pageSize=10){if(!total)return'';const last=Math.min(start+count,total),pages=Math.max(1,Math.ceil(total/pageSize));return`<nav class="list-pagination"><span>${start+1}–${last} sur ${total}</span><button class="icon-button" onclick="${handler}(-1)" ${page<=1?'disabled':''}>‹</button><button class="icon-button" onclick="${handler}(1)" ${page>=pages?'disabled':''}>›</button></nav>`}
function formatDate(value){return value?new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'Jamais'}
function downloadCsv(name,rows){const cell=value=>`"${String(value??'').replace(/"/g,'""').replace(/[\r\n]+/g,' ')}"`,blob=new Blob([`\uFEFF${rows.map(row=>row.map(cell).join(';')).join('\r\n')}\r\n`],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
function showError(error){alert(error.message)}

async function openPanel(id,button){activePanel=id;document.querySelectorAll('.panel').forEach(panel=>panel.classList.toggle('active',panel.id===id));document.querySelectorAll('.nav-button').forEach(item=>item.classList.remove('active'));button?.classList.add('active');try{if(id==='instructors')await loadInstructors();if(id==='archives')await loadArchives();if(id==='journal')await loadJournal()}catch(error){showError(error)}}
async function logout(){await signOut();profile=null;login()}

async function start(){if(!getSession())return login();try{profile=await getInstructorProfile();if(profile.role!=='superadmin'){shell('<div class="login"><div class="notice"><b>Accès refusé.</b><p>Cette page est réservée au superadministrateur.</p><a class="button" href="./instructor.html">Retour à l’espace instructeur</a></div></div>');return}layout();await openPanel(activePanel,document.querySelector('.nav-button.active'))}catch(error){if(error.status===401)return login();showError(error)}}

Object.assign(window,{doLogin,openPanel,submitInstructor,changeInstructorStatus,changeInstructorPassword,changeArchivePage,restoreItem,deleteItem,exportArchives,searchJournal,changeAuditPage,exportJournal,logout});
start();
